"""The pull-request body template idle-loop renders for every PR it opens.

Designed to grow: a PR section is just a function ``(PRContent) -> str`` that
returns its Markdown (or ``""`` to omit itself). To add a section, write the
function and drop it into :data:`SECTIONS` at the position you want it; to
reorder, move the entries. :func:`render_pr_body` stitches the non-empty
sections together and appends the footer.

Kept rendering-only and dependency-light: the orchestrator passes in the bits
it has already computed (the cost badges, the gates summary) so this module
doesn't reach back into the loop or the GitHub client.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field

# The PLG sign-off. Bare URL kept so it renders the same everywhere.
FOOTER = (
    "🤖 Generated by [idle](https://github.com/viksuper555/idle-loop) — "
    "the guard-railed autonomous coding loop."
)


@dataclass
class PRContent:
    """Everything a PR section might want, pre-computed by the orchestrator."""

    issue_number: int
    title: str = ""
    branch: str = ""
    issue_url: str = ""
    acceptance_criteria: list[str] = field(default_factory=list)
    files_changed: int = 0
    iterations: int = 0
    cost_badges_md: str = ""  # the est/actual cost + tokens shields block
    gates_md: str = ""  # the rendered guard-gates summary
    commentary: str = ""  # the implementer's closing notes


# --------------------------------------------------------------------------- #
# Sections — each takes the PRContent and returns Markdown ("" to skip).
# --------------------------------------------------------------------------- #
def summary_section(c: PRContent) -> str:
    """Link back to the source of truth: the issue and its summary."""
    lines = [f"Closes #{c.issue_number}"]
    link = f"[#{c.issue_number}]({c.issue_url})" if c.issue_url else f"#{c.issue_number}"
    title = f" — {c.title}" if c.title else ""
    lines.append(f"\n**Summary:** {link}{title}")
    if c.branch:
        lines.append(f"**Branch:** `{c.branch}`")
    return "\n".join(lines)


def acceptance_section(c: PRContent) -> str:
    """The acceptance criteria as a checklist a reviewer can tick off."""
    if not c.acceptance_criteria:
        return ""
    items = "\n".join(f"- [ ] {a}" for a in c.acceptance_criteria)
    return f"### Acceptance criteria\n{items}"


def cost_section(c: PRContent) -> str:
    """The cost estimate vs. actual chips (plus iteration/file counts)."""
    if not c.cost_badges_md:
        return ""
    stats = f"_{c.files_changed} file(s) · {c.iterations} iteration(s)._"
    return f"### Cost\n{c.cost_badges_md}\n\n{stats}"


def gates_section(c: PRContent) -> str:
    """The fail-closed guard results."""
    return c.gates_md or ""


def commentary_section(c: PRContent) -> str:
    """The implementer's closing notes on what it did."""
    note = (c.commentary or "").strip()
    if not note:
        return ""
    return f"### Commentary\n{note}"


# Order = order they appear in the PR. Append here to grow the template.
SECTIONS: list[Callable[[PRContent], str]] = [
    summary_section,
    acceptance_section,
    cost_section,
    gates_section,
    commentary_section,
]


def render_pr_body(content: PRContent) -> str:
    """Render the full PR body: every non-empty section, then the footer."""
    blocks = [section(content) for section in SECTIONS]
    blocks = [b.strip() for b in blocks if b and b.strip()]
    blocks.append(FOOTER)
    return "\n\n".join(blocks)
